MENU_ITEMS = [
    {"name": "Paneer Tikka", "category": "Tandoor Specials", "price": 230, "aliases": ["paneer tikka"]},
    {"name": "Chicken Tikka", "category": "Tandoor Specials", "price": 220, "aliases": ["chicken tikka"]},
    {"name": "Chicken Reshmi Tikka", "category": "Tandoor Specials", "price": 250, "aliases": ["reshmi tikka", "chicken reshmi tikka"]},
    {"name": "Chicken Tandoori Half", "category": "Tandoor Specials", "price": 250, "aliases": ["half tandoori", "chicken tandoori half"]},
    {"name": "Chicken Tandoori Full", "category": "Tandoor Specials", "price": 450, "aliases": ["full tandoori", "chicken tandoori full"]},
    {"name": "Chicken Seekh Kebab", "category": "Tandoor Specials", "price": 230, "aliases": ["chicken seekh kebab", "seekh kebab chicken"]},
    {"name": "Veg Seekh Kebab", "category": "Tandoor Specials", "price": 180, "aliases": ["veg seekh kebab"]},
    {"name": "Chhola Bhatura", "category": "Snacks & Starters", "price": 50, "aliases": ["chhola bhatura", "chole bhature", "chole bhatura"]},
    {"name": "Onion Pakoda", "category": "Snacks & Starters", "price": 100, "aliases": ["onion pakoda"]},
    {"name": "Veg Pakoda", "category": "Snacks & Starters", "price": 180, "aliases": ["veg pakoda"]},
    {"name": "Paneer Pakoda", "category": "Snacks & Starters", "price": 200, "aliases": ["paneer pakoda"]},
    {"name": "Chicken Pakoda Boneless", "category": "Snacks & Starters", "price": 210, "aliases": ["chicken pakoda", "boneless chicken pakoda"]},
    {"name": "Chicken Lollipop", "category": "Snacks & Starters", "price": 150, "aliases": ["chicken lollipop", "lollipop"]},
    {"name": "Chicken Chilli", "category": "Indo-Chinese", "price": 220, "aliases": ["chicken chilli", "chilli chicken"]},
    {"name": "Chicken Manchurian", "category": "Indo-Chinese", "price": 250, "aliases": ["chicken manchurian"]},
    {"name": "Paneer Chilli", "category": "Indo-Chinese", "price": 290, "aliases": ["paneer chilli", "chilli paneer"]},
    {"name": "Veg Manchurian", "category": "Indo-Chinese", "price": 120, "aliases": ["veg manchurian"]},
    {"name": "Veg Chowmein", "category": "Chowmein", "price": 60, "aliases": ["veg chowmein"]},
    {"name": "Egg Chowmein", "category": "Chowmein", "price": 80, "aliases": ["egg chowmein"]},
    {"name": "Egg Chicken Chowmein", "category": "Chowmein", "price": 120, "aliases": ["egg chicken chowmein", "chicken egg chowmein"]},
    {"name": "Veg Roll", "category": "Rolls", "price": 50, "aliases": ["veg roll"]},
    {"name": "Egg Roll", "category": "Rolls", "price": 60, "aliases": ["egg roll"]},
    {"name": "Paneer Roll", "category": "Rolls", "price": 90, "aliases": ["paneer roll"]},
    {"name": "Egg Chicken Roll", "category": "Rolls", "price": 100, "aliases": ["egg chicken roll", "chicken egg roll"]},
    {"name": "Chicken Spring Roll", "category": "Rolls", "price": 80, "aliases": ["chicken spring roll"]},
    {"name": "Veg Thali Simple", "category": "Thali", "price": 70, "aliases": ["simple veg thali", "veg thali simple"]},
    {"name": "Veg Thali", "category": "Thali", "price": 120, "aliases": ["veg thali"]},
    {"name": "Mutton Thali", "category": "Thali", "price": 220, "aliases": ["mutton thali"]},
    {"name": "Chicken Biryani", "category": "Biryani", "price": 150, "aliases": ["chicken biryani"]},
    {"name": "Egg Biryani", "category": "Biryani", "price": 130, "aliases": ["egg biryani"]},
    {"name": "Mutton Biryani", "category": "Biryani", "price": 250, "aliases": ["mutton biryani"]},
    {"name": "Paneer Masala", "category": "Main Course", "price": 200, "aliases": ["paneer masala"]},
    {"name": "Paneer Butter Masala", "category": "Main Course", "price": 220, "aliases": ["paneer butter masala", "pbm"]},
    {"name": "Paneer Kadhai", "category": "Main Course", "price": 246, "aliases": ["paneer kadhai", "kadhai paneer"]},
    {"name": "Paneer Handi", "category": "Main Course", "price": 256, "aliases": ["paneer handi"]},
    {"name": "Mix Veg", "category": "Main Course", "price": 200, "aliases": ["mix veg"]},
    {"name": "Mushroom Masala", "category": "Main Course", "price": 190, "aliases": ["mushroom masala"]},
    {"name": "Chicken Masala", "category": "Main Course", "price": 226, "aliases": ["chicken masala"]},
    {"name": "Chicken Butter Masala", "category": "Main Course", "price": 250, "aliases": ["chicken butter masala"]},
    {"name": "Dal Tadka", "category": "Main Course", "price": 80, "aliases": ["dal tadka"]},
    {"name": "Steam Rice", "category": "Rice", "price": 40, "aliases": ["steam rice", "plain rice"]},
    {"name": "Jeera Rice", "category": "Rice", "price": 70, "aliases": ["jeera rice"]},
    {"name": "Veg Fried Rice", "category": "Rice", "price": 100, "aliases": ["veg fried rice"]},
    {"name": "Egg Fried Rice", "category": "Rice", "price": 110, "aliases": ["egg fried rice"]},
    {"name": "Paneer Fried Rice", "category": "Rice", "price": 150, "aliases": ["paneer fried rice"]},
    {"name": "Egg Chicken Fried Rice", "category": "Rice", "price": 170, "aliases": ["egg chicken fried rice", "chicken egg fried rice"]},
    {"name": "Tawa Roti", "category": "Roti & Bread", "price": 10, "aliases": ["tawa roti", "roti"]},
    {"name": "Tandoori Roti", "category": "Roti & Bread", "price": 15, "aliases": ["tandoori roti"]},
    {"name": "Plain Naan", "category": "Roti & Bread", "price": 30, "aliases": ["plain naan", "naan"]},
    {"name": "Butter Naan", "category": "Roti & Bread", "price": 40, "aliases": ["butter naan"]},
    {"name": "Garlic Naan", "category": "Roti & Bread", "price": 60, "aliases": ["garlic naan"]},
    {"name": "Masala Kulcha", "category": "Roti & Bread", "price": 70, "aliases": ["masala kulcha"]},
    {"name": "Paneer Kulcha", "category": "Roti & Bread", "price": 80, "aliases": ["paneer kulcha"]},
    {"name": "Laacha Paratha", "category": "Roti & Bread", "price": 50, "aliases": ["laacha paratha", "lachha paratha"]},
    {"name": "Veg Momo", "category": "Momos", "price": 150, "aliases": ["veg momo", "veg momos"]},
    {"name": "Chicken Momo", "category": "Momos", "price": 150, "aliases": ["chicken momo", "chicken momos"]},
    {"name": "Veg Tandoori Momo", "category": "Momos", "price": 120, "aliases": ["veg tandoori momo", "veg tandoori momos"]},
    {"name": "Chicken Tandoori Momo", "category": "Momos", "price": 150, "aliases": ["chicken tandoori momo", "chicken tandoori momos"]},
    {"name": "Masala Dosa", "category": "Dosa", "price": 60, "aliases": ["masala dosa"]},
    {"name": "Paneer Dosa", "category": "Dosa", "price": 100, "aliases": ["paneer dosa"]},
    {"name": "Plain Dosa", "category": "Dosa", "price": 50, "aliases": ["plain dosa"]},
    {"name": "Idli", "category": "Dosa", "price": 10, "aliases": ["idli"]},
    {"name": "Cheese Pizza", "category": "Pizza", "price": 140, "aliases": ["cheese pizza"]},
    {"name": "Classic Pizza", "category": "Pizza", "price": 160, "aliases": ["classic pizza"]},
    {"name": "Paneer Pizza", "category": "Pizza", "price": 160, "aliases": ["paneer pizza"]},
    {"name": "Corn Pizza", "category": "Pizza", "price": 160, "aliases": ["corn pizza"]},
    {"name": "Mushroom Pizza", "category": "Pizza", "price": 210, "aliases": ["mushroom pizza"]},
    {"name": "Veg Street Burger", "category": "Burgers", "price": 45, "aliases": ["veg street burger"]},
    {"name": "Veg Amazing Burger", "category": "Burgers", "price": 65, "aliases": ["veg amazing burger"]},
    {"name": "Eggy Burger", "category": "Burgers", "price": 95, "aliases": ["eggy burger"]},
    {"name": "Amazing Egg Burger", "category": "Burgers", "price": 110, "aliases": ["amazing egg burger"]},
    {"name": "Chicken Burger", "category": "Burgers", "price": 120, "aliases": ["chicken burger"]},
]
